---
name: hhdeploy package
'on':
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]  # cache from master shared with child branches

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        poetry-version: ["<1.8", "<1.9"]

    steps:
      - uses: actions/checkout@v4

      - name: Install python
        id: venv
        uses: getsentry/action-setup-venv@a133e6fd5fa6abd3f590a1c106abda344f5df69f
        with:
          python-version: ${{ matrix.python-version }}
          cache-dependency-path: |
            .github/requirements-test.txt

      - name: Install package
        run: |
          python -m pip install -r .github/requirements-test.txt "poetry${{ matrix.poetry-version }}"
          python -m poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: 'false'

      - name: Test with pytest
        run: |
          python -m pytest

      - name: Check syntax
        run: |
          python -m ruff check poetry_source_env
          python -m ruff format --check poetry_source_env
          python -m mypy poetry_source_env
        env:
          RUFF_OUTPUT_FORMAT: github
